import fs from "node:fs";
import path from "node:path";
import React from "react";
import { renderToString } from "react-dom/server";
import {
  App as AntdApp,
  Button,
  ConfigProvider,
  Drawer,
  Input,
  Result,
  Select,
  Spin,
  Switch,
  Tag,
  Typography,
} from "antd";
import { createCache, extractStyle, StyleProvider } from "@ant-design/cssinjs";
import enUS from "antd/locale/en_US";
import zhCN from "antd/locale/zh_CN";
import {
  DEVFLEET_ANTD_COMPAT_TRANSFORMERS,
  DEVFLEET_DARK_ANTD_THEME,
  DEVFLEET_LIGHT_ANTD_THEME,
} from "../src/theme/antdTheme";

const OUTPUT_PATH = path.resolve(
  process.cwd(),
  "src/generated/antd-static.css",
);

function StaticAntdStyleFixture() {
  return React.createElement(
    React.Fragment,
    null,
    React.createElement(
      "div",
      { style: { padding: 16 } },
      React.createElement(
        "div",
        { style: { display: "flex", gap: 12, marginBottom: 12 } },
        React.createElement(Button, { type: "primary" }, "Primary"),
        React.createElement(Button, null, "Default"),
        React.createElement(Button, { danger: true }, "Danger"),
        React.createElement(Switch, { checked: true }),
        React.createElement(Tag, { color: "processing" }, "Tag"),
      ),
      React.createElement(
        "div",
        { style: { display: "grid", gap: 12 } },
        React.createElement(Input, { placeholder: "Search projects..." }),
        React.createElement(Input.Search, {
          placeholder: "Search node version...",
          allowClear: true,
        }),
        React.createElement(Select, {
          style: { width: 220 },
          defaultValue: "dev",
          options: [
            { label: "dev", value: "dev" },
            { label: "build", value: "build" },
          ],
        }),
        React.createElement(
          Typography.Paragraph,
          null,
          "/Users/example/project",
        ),
        React.createElement(Spin, { spinning: true }),
      ),
      React.createElement(
        Drawer,
        {
          open: false,
          forceRender: true,
          getContainer: false,
          title: "Node Version Manager",
          width: 420,
        },
        React.createElement(Input, {
          placeholder: "Search versions...",
          allowClear: true,
        }),
      ),
      React.createElement(Result, {
        status: "info",
        title: "Empty State",
        subTitle: "Static style extraction keeps packaged builds stable.",
      }),
    ),
  );
}

function renderThemeSnapshot(
  locale: typeof zhCN,
  themeConfig: typeof DEVFLEET_LIGHT_ANTD_THEME,
) {
  return React.createElement(
    ConfigProvider,
    { locale, theme: themeConfig },
    React.createElement(
      AntdApp,
      null,
      React.createElement(StaticAntdStyleFixture),
    ),
  );
}

function collectStyles() {
  const snapshots = [
    renderThemeSnapshot(zhCN, DEVFLEET_LIGHT_ANTD_THEME),
    renderThemeSnapshot(enUS, DEVFLEET_DARK_ANTD_THEME),
  ];

  const cssChunks = snapshots.map((snapshot) => {
    const cache = createCache();
    renderToString(
      React.createElement(
        StyleProvider,
        {
          cache,
          hashPriority: "high",
          transformers: DEVFLEET_ANTD_COMPAT_TRANSFORMERS,
        },
        snapshot,
      ),
    );
    return extractStyle(cache, {
      plain: true,
      types: ["style", "token", "cssVar"],
    });
  });

  return cssChunks.join("\n");
}

function main() {
  const css = collectStyles();
  const banner =
    "/* This file is auto-generated by scripts/generate-antd-static-css.tsx. */\n";

  fs.mkdirSync(path.dirname(OUTPUT_PATH), { recursive: true });
  fs.writeFileSync(OUTPUT_PATH, `${banner}${css}`);
  console.log(`[antd-css] wrote ${path.relative(process.cwd(), OUTPUT_PATH)}`);
}

main();
